-- Enable Row Level Security
ALTER DATABASE postgres SET "app.jwt_secret" TO 'your-jwt-secret';

-- Create managers table
CREATE TABLE public.managers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    phone text NULL,
    email text NULL,
    avatar text NULL,
    experience text NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT managers_pkey PRIMARY KEY (id)
);

-- Create hostels table
CREATE TABLE public.hostels (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    address text NULL,
    rooms integer NULL,
    occupancy integer NULL,
    manager_id bigint NULL,
    type text NULL,
    note text NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT hostels_pkey PRIMARY KEY (id),
    CONSTRAINT hostels_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES managers(id)
);

-- Create tenants table
CREATE TABLE public.tenants (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    room_number text NULL,
    address text NULL,
    phone text NULL,
    emergency_phone text NULL,
    months_rented integer NULL,
    status text NULL,
    hostel_id bigint NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_hostel_id_fkey FOREIGN KEY (hostel_id) REFERENCES hostels(id)
);

-- Create employees table
CREATE TABLE public.employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    position text NULL,
    department text NULL,
    salary numeric NULL,
    hire_date date NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

-- Create notifications table
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title text NULL,
    message text NULL,
    type text NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

-- Create revenue_data table
CREATE TABLE public.revenue_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    month text NULL,
    amount numeric NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT revenue_data_pkey PRIMARY KEY (id)
);

-- Create expense_categories table
CREATE TABLE public.expense_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category text NULL,
    amount numeric NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT expense_categories_pkey PRIMARY KEY (id)
);

-- Create hostels_view for combined data
CREATE VIEW hostels_view AS
SELECT
    h.id,
    h.name,
    h.address,
    h.rooms,
    h.occupancy,
    h.type,
    h.note,
    h.created_at,
    h.updated_at,
    json_build_object(
        'id', m.id,
        'name', m.name,
        'phone', m.phone,
        'email', m.email,
        'avatar', m.avatar,
        'experience', m.experience
    ) as manager
FROM
    hostels h
LEFT JOIN
    managers m ON h.manager_id = m.id;

-- Enable Row Level Security
ALTER TABLE public.managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hostels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;

-- Create policies (allow all for now - you can restrict later)
CREATE POLICY "Enable all operations for managers" ON public.managers FOR ALL USING (true);
CREATE POLICY "Enable all operations for hostels" ON public.hostels FOR ALL USING (true);
CREATE POLICY "Enable all operations for tenants" ON public.tenants FOR ALL USING (true);
CREATE POLICY "Enable all operations for employees" ON public.employees FOR ALL USING (true);
CREATE POLICY "Enable all operations for notifications" ON public.notifications FOR ALL USING (true);
CREATE POLICY "Enable all operations for revenue_data" ON public.revenue_data FOR ALL USING (true);
CREATE POLICY "Enable all operations for expense_categories" ON public.expense_categories FOR ALL USING (true);

-- Insert sample data
INSERT INTO public.managers (name, phone, email, avatar, experience) VALUES
('Nguyễn Văn A', '0901234567', 'manager1@example.com', '', '5 năm quản lý khu trọ'),
('Trần Thị B', '0907654321', 'manager2@example.com', '', '3 năm kinh nghiệm');

INSERT INTO public.hostels (name, address, rooms, occupancy, manager_id, type, note) VALUES
('Khu trọ An Phú', '123 Đường An Phú, Quận 2, TP.HCM', 20, 15, 1, 'standard', 'Khu trọ tiêu chuẩn với đầy đủ tiện nghi'),
('Khu trọ Bình Thạnh', '456 Đường Bình Thạnh, Quận Bình Thạnh, TP.HCM', 15, 12, 2, 'premium', 'Khu trọ cao cấp với nhiều tiện ích');

INSERT INTO public.tenants (name, room_number, address, phone, emergency_phone, months_rented, status, hostel_id) VALUES
('Lê Văn C', 'A101', '123 Đường An Phú, Quận 2, TP.HCM', '0901111111', '0902222222', 6, 'active', 1),
('Phạm Thị D', 'A102', '123 Đường An Phú, Quận 2, TP.HCM', '0903333333', '0904444444', 3, 'active', 1),
('Hoàng Văn E', 'B201', '456 Đường Bình Thạnh, Quận Bình Thạnh, TP.HCM', '0905555555', '0906666666', 12, 'active', 2);

INSERT INTO public.employees (name, position, department, salary, hire_date) VALUES
('Nguyễn Văn F', 'Bảo vệ', 'An ninh', 8000000, '2023-01-15'),
('Trần Thị G', 'Vệ sinh', 'Dịch vụ', 6000000, '2023-02-01'),
('Lê Văn H', 'Bảo trì', 'Kỹ thuật', 10000000, '2023-01-20');

INSERT INTO public.notifications (title, message, type, is_read) VALUES
('Thông báo bảo trì', 'Sẽ có bảo trì hệ thống điện vào ngày 15/12', 'maintenance', false),
('Cập nhật giá thuê', 'Giá thuê phòng sẽ tăng từ tháng 1/2024', 'price', false),
('Lịch thanh toán', 'Nhắc nhở thanh toán tiền thuê tháng 12', 'payment', false);

INSERT INTO public.revenue_data (month, amount) VALUES
('Tháng 1', 50000000),
('Tháng 2', 52000000),
('Tháng 3', 48000000),
('Tháng 4', 55000000),
('Tháng 5', 58000000),
('Tháng 6', 60000000);

INSERT INTO public.expense_categories (category, amount) VALUES
('Điện nước', 15000000),
('Bảo trì', 8000000),
('Lương nhân viên', 12000000),
('Vật tư', 5000000),
('Khác', 3000000);
