export interface AddTenantDialogProps {
    isOpen: boolean
    onOpenChange: (open: boolean) => void
    onAddTenant: (payload: any) => void
    selectedHostel?: any
}

export interface Room {
    id: number
    room_number: string
    room_type: string
    rent_amount: number
    status: 'available' | 'occupied'
    hostel_id: number
}

export interface TenantFormData {
    name: string
    address: string
    phone: string
    email?: string
    cccd?: string
    rentMonths: number
}

export interface TenantPayload {
    name: string
    roomNumber: string
    address: string
    phone: string
    rentMonths: number
    roomId: number
    roomType: string
    rentAmount: number
    khachThueId: number
    hopDongId: number
}

export interface ValidationResult {
    isValid: boolean
    errorMessage?: string
}

export interface ContractInfo {
    startDate: string
    endDate: string
    rentMonths: number
    isAutoGenerated: boolean
}
