import { TenantFormData, Room, ValidationResult, ContractInfo } from '../types/tenant.types'

/**
 * Validate tenant form data
 */
export function validateTenantForm(formData: TenantFormData, selectedRoom: Room | null): ValidationResult {
    if (!formData.name.trim()) {
        return {
            isValid: false,
            errorMessage: 'Vui lòng nhập tên khách thuê'
        }
    }

    if (!formData.phone.trim()) {
        return {
            isValid: false,
            errorMessage: 'Vui lòng nhập số điện thoại'
        }
    }

    if (!selectedRoom) {
        return {
            isValid: false,
            errorMessage: 'Vui lòng chọn phòng từ danh sách gợi ý'
        }
    }

    if (selectedRoom.status !== 'available') {
        return {
            isValid: false,
            errorMessage: `Phòng ${selectedRoom.room_number} đã có người thuê. Vui lòng chọn phòng khác.`
        }
    }

    if (formData.email && formData.email.trim() && !formData.email.includes('@')) {
        return {
            isValid: false,
            errorMessage: 'Email không hợp lệ'
        }
    }

    if (formData.rentMonths <= 0) {
        return {
            isValid: false,
            errorMessage: 'Số tháng thuê phải lớn hơn 0'
        }
    }

    return { isValid: true }
}

/**
 * Filter rooms based on search term
 */
export function filterRooms(rooms: Room[], searchTerm: string): Room[] {
    if (!searchTerm.trim()) return rooms

    return rooms.filter(room =>
        room.room_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
        room.room_type.toLowerCase().includes(searchTerm.toLowerCase())
    )
}

/**
 * Generate contract information
 */
export function generateContractInfo(rentMonths: number): ContractInfo {
    const today = new Date()
    const startDate = today.toISOString().split('T')[0]
    const endDate = new Date(
        today.getFullYear(),
        today.getMonth() + rentMonths,
        today.getDate()
    ).toISOString().split('T')[0]

    return {
        startDate,
        endDate,
        rentMonths,
        isAutoGenerated: true
    }
}

/**
 * Format currency for Vietnamese locale
 */
export function formatCurrency(amount: number): string {
    return amount.toLocaleString('vi-VN') + '₫'
}

/**
 * Format date for Vietnamese locale
 */
export function formatDate(dateString: string): string {
    const date = new Date(dateString)
    return date.toLocaleDateString('vi-VN')
}

/**
 * Generate unified contract HTML used by both Manager and Tenant
 */
export function buildContractHtml(payload: {
    hostelName?: string
    roomNumber?: string
    tenantName?: string
    phone?: string
    email?: string
    startDate?: string
    endDate?: string
    rentAmount?: number
    contractId?: any
    managerName?: string
    managerPhone?: string
    managerEmail?: string
}): string {
    const {
        hostelName = '-',
        roomNumber = '-',
        tenantName = '-',
        phone = '-',
        email = '-',
        startDate = '',
        rentAmount = 0,
        contractId,
        managerName = '-',
        managerPhone = '-',
        managerEmail = '-'
    } = payload

    const currentDate = new Date().toLocaleDateString('vi-VN')
    const contractStartDate = startDate ? formatDate(startDate) : '-'

    return `
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hợp đồng thuê phòng</title>
    <style>
        body {
            font-family: 'Times New Roman', serif;
            line-height: 1.6;
            color: #333;
            background: #f8f9fa;
            margin: 0;
            padding: 20px;
        }
        .contract-container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .republic {
            font-size: 16px;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 10px;
        }
        .motto {
            font-size: 14px;
            font-style: italic;
            margin-bottom: 20px;
        }
        .date-place {
            text-align: right;
            margin-bottom: 30px;
            font-style: italic;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .legal-basis {
            margin-bottom: 20px;
            font-size: 14px;
        }
        .legal-basis p {
            margin: 5px 0;
        }
        .parties-section {
            margin-bottom: 25px;
        }
        .party {
            margin-bottom: 20px;
        }
        .party-title {
            font-weight: bold;
            font-size: 16px;
            margin-bottom: 10px;
            color: #1e40af;
        }
        .party-info {
            margin-left: 20px;
            line-height: 1.8;
        }
        .article {
            margin-bottom: 25px;
        }
        .article-title {
            font-size: 16px;
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 10px;
        }
        .article-content {
            margin-left: 20px;
            line-height: 1.7;
        }
        .article-content p {
            margin: 8px 0;
        }
        .article-content strong {
            color: #374151;
        }
        .signature-section {
            margin-top: 40px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 40px;
        }
        .signature-box {
            text-align: center;
        }
        .signature-line {
            border-bottom: 1px solid #374151;
            height: 40px;
            margin-bottom: 10px;
        }
        .signature-label {
            font-weight: bold;
            color: #374151;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 14px;
        }
        .highlight {
            background: #fef3c7;
            padding: 2px 4px;
            border-radius: 3px;
            font-weight: bold;
        }
        .amount {
            color: #dc2626;
            font-weight: bold;
        }
        @media print {
            body { background: white; }
            .contract-container { box-shadow: none; }
        }
    </style>
</head>
<body>
    <div class="contract-container">
        <div class="header">
            <div class="republic">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
            <div class="motto">Độc lập - Tự do - Hạnh phúc</div>
            <div class="date-place">………., ngày ${new Date().getDate()} tháng ${new Date().getMonth() + 1} năm ${new Date().getFullYear()}</div>
        </div>

        <div class="title">HỢP ĐỒNG THUÊ PHÒNG</div>

        <div class="legal-basis">
            <p>- Căn cứ Bộ luật Dân sự số 91/2015/QH13 ngày 24/11/2015;</p>
            <p>- Căn cứ vào Luật Thương mại số 36/2005/QH11 ngày 14 tháng 06 năm 2005;</p>
            <p>- Căn cứ vào nhu cầu và sự thỏa thuận của các bên tham gia Hợp đồng;</p>
        </div>

        <div class="parties-section">
            <p>Hôm nay, ngày ${new Date().getDate()} tháng ${new Date().getMonth() + 1} năm ${new Date().getFullYear()}, các Bên gồm:</p>
            
            <div class="party">
                <div class="party-title">BÊN CHO THUÊ (Bên A):</div>
                <div class="party-info">
                    <p>Ông/Bà: ${managerName || '................................'}</p>
                    <p>CMND/CCCD số:................ Cơ quan cấp:………...……….. Ngày cấp:..............</p>
                    <p>Nơi ĐKTT:........................................................................................</p>
                    <p>Địa chỉ: ${hostelName || '................................'}</p>
                    <p>Số điện thoại: ${managerPhone || '................................'}</p>
                    <p>Email: ${managerEmail || '................................'}</p>
                </div>
            </div>

            <div class="party">
                <div class="party-title">BÊN THUÊ (Bên B):</div>
                <div class="party-info">
                    <p>Ông/Bà: ${tenantName || '................................'}</p>
                    <p>CMND/CCCD số:................ Cơ quan cấp:………...……….. Ngày cấp:..............</p>
                    <p>Nơi ĐKTT:........................................................................................</p>
                    <p>Số điện thoại: ${phone || '................................'}</p>
                    <p>Email: ${email || '................................'}</p>
                </div>
            </div>

            <p>Bên A và Bên B sau đây gọi chung là "Hai Bên" hoặc "Các Bên".</p>
            <p>Sau khi thảo luận, Hai Bên thống nhất đi đến ký kết Hợp đồng thuê phòng ("Hợp Đồng") với các điều khoản và điều kiện dưới đây:</p>
        </div>

        <div class="article">
            <div class="article-title">Điều 1. Phòng ở và các tài sản cho thuê kèm theo:</div>
            <div class="article-content">
                <p><strong>1.1.</strong> Bên A đồng ý cho Bên B thuê và Bên B cũng đồng ý thuê phòng số <strong>${roomNumber || '.........'}</strong> tại địa chỉ <strong>${hostelName || '................................'}</strong> để sử dụng làm nơi ở.</p>
                <p><strong>1.2.</strong> Bên A cam kết phòng cho thuê trên là tài sản sở hữu hợp pháp của Bên A. Mọi tranh chấp phát sinh từ tài sản cho thuê trên Bên A hoàn toàn chịu trách nhiệm trước pháp luật.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 2. Bàn giao và sử dụng diện tích thuê:</div>
            <div class="article-content">
                <p><strong>2.1.</strong> Thời điểm Bên A bàn giao phòng thuê vào ngày <strong>${contractStartDate}</strong>;</p>
                <p><strong>2.2.</strong> Bên B được toàn quyền sử dụng phòng thuê kể từ thời điểm được Bên A bàn giao từ thời điểm quy định tại Mục 2.1 trên đây.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 3. Thời hạn thuê:</div>
            <div class="article-content">
                <p><strong>3.1.</strong> Bên A cam kết cho Bên B thuê phòng với thời hạn là <strong>12 tháng</strong> kể từ ngày bàn giao phòng thuê;</p>
                <p><strong>3.2.</strong> Hết thời hạn thuê nêu trên nếu bên B có nhu cầu tiếp tục sử dụng thì Bên A phải ưu tiên cho Bên B tiếp tục thuê.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 4. Đặt cọc tiền thuê phòng:</div>
            <div class="article-content">
                <p><strong>4.1.</strong> Bên B sẽ giao cho Bên A một khoản tiền là <strong>${formatCurrency(rentAmount || 0)}</strong> (bằng chữ: <strong>................................</strong>) ngay sau khi ký hợp đồng này. Số tiền này là tiền đặt cọc để đảm bảm thực hiện Hợp đồng cho thuê phòng.</p>
                <p><strong>4.2.</strong> Nếu Bên B đơn phương chấm dứt hợp đồng mà không thực hiện nghĩa vụ báo trước tới Bên A thì Bên A sẽ không phải hoàn trả lại Bên B số tiền đặt cọc này.</p>
                <p><strong>4.3.</strong> Tiền đặt cọc của Bên B sẽ không được dùng để thanh toán tiền thuê. Nếu Bên B vi phạm Hợp Đồng làm phát sinh thiệt hại cho Bên A thì Bên A có quyền khấu trừ tiền đặt cọc để bù đắp các chi phí khắc phục thiệt hại phát sinh.</p>
                <p><strong>4.4.</strong> Vào thời điểm kết thúc thời hạn thuê hoặc kể từ ngày chấm dứt Hợp đồng, Bên A sẽ hoàn lại cho Bên B số tiền đặt cọc sau khi đã khấu trừ khoản tiền chi phí để khắc phục thiệt hại (nếu có).</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 5. Tiền thuê phòng:</div>
            <div class="article-content">
                <p><strong>5.1.</strong> Tiền thuê phòng đối với phòng thuê nêu tại mục 1.1 Điều 1 là: <strong>${formatCurrency(rentAmount || 0)}/tháng</strong> (Bằng chữ: <strong>................................</strong>)</p>
                <p><strong>5.2.</strong> Tiền thuê phòng không bao gồm chi phí khác như tiền điện, nước, vệ sinh.... Khoản tiền này sẽ do bên B trả theo khối lượng, công suất sử dụng thực tế của Bên B hàng tháng, được tính theo đơn giá của nhà nước.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 6. Phương thức thanh toán tiền thuê phòng:</div>
            <div class="article-content">
                <p>Tiền thuê phòng được thanh toán theo <strong>01 (một) tháng/lần</strong> vào ngày <strong>05 (năm)</strong> hàng tháng.</p>
                <p>Các chi phí khác được bên B tự thanh toán với các cơ quan, đơn vị có liên quan khi được yêu cầu.</p>
                <p>Việc thanh toán tiền thuê phòng được thực hiện bằng đồng tiền Việt Nam theo hình thức trả trực tiếp bằng tiền mặt.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 7. Quyền và nghĩa vụ của bên cho thuê phòng:</div>
            <div class="article-content">
                <p><strong>7.1. Quyền lợi:</strong></p>
                <p>- Yêu cầu Bên B thanh toán tiền thuê và chi phí khác đầy đủ, đúng hạn theo thoả thuận trong Hợp Đồng;</p>
                <p>- Yêu cầu Bên B phải sửa chữa phần hư hỏng, thiệt hại do lỗi của Bên B gây ra.</p>
                <p><strong>7.2. Nghĩa vụ:</strong></p>
                <p>- Bàn giao phòng thuê cho Bên B theo đúng thời gian quy định trong Hợp đồng;</p>
                <p>- Đảm bảo việc cho thuê theo Hợp đồng này là đúng quy định của pháp luật;</p>
                <p>- Đảm bảo cho Bên B thực hiện quyền sử dụng phòng thuê một cách độc lập và liên tục trong suốt thời hạn thuê;</p>
                <p>- Không xâm phạm trái phép đến tài sản của Bên B trong phần phòng thuê;</p>
                <p>- Tuân thủ các nghĩa vụ khác theo thoả thuận tại Hợp đồng này.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 8. Quyền và nghĩa vụ của bên thuê phòng:</div>
            <div class="article-content">
                <p><strong>8.1. Quyền lợi:</strong></p>
                <p>- Nhận bàn giao phòng thuê theo đúng thoả thuận trong Hợp đồng;</p>
                <p>- Được sử dụng phòng thuê làm nơi ở và các hoạt động hợp pháp khác;</p>
                <p>- Yêu cầu Bên A sửa chữa kịp thời những hư hỏng không phải do lỗi của Bên B trong phòng thuê;</p>
                <p>- Được tháo dỡ và đem ra khỏi phòng thuê các tài sản, trang thiết bị của Bên B đã lắp đặt trong phòng thuê khi hết thời hạn thuê.</p>
                <p><strong>8.2. Nghĩa vụ:</strong></p>
                <p>- Sử dụng phòng thuê đúng mục đích đã thỏa thuận, giữ gìn phòng ở và có trách nhiệm trong việc sửa chữa những hư hỏng do mình gây ra;</p>
                <p>- Thanh toán tiền đặt cọc, tiền thuê đầy đủ, đúng thời hạn đã thỏa thuận;</p>
                <p>- Trả lại phòng thuê cho Bên A khi hết thời hạn thuê hoặc chấm dứt Hợp đồng thuê;</p>
                <p>- Mọi việc sửa chữa, cải tạo, lắp đặt bổ sung các trang thiết bị làm ảnh hưởng đến kết cấu của phòng, Bên B phải có văn bản thông báo cho Bên A và chỉ được tiến hành các công việc này sau khi có sự đồng ý bằng văn bản của Bên A;</p>
                <p>- Tuân thủ một cách chặt chẽ quy định tại Hợp đồng này và các quy định của pháp luật Việt Nam.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 9. Đơn phương chấm dứt hợp đồng thuê phòng:</div>
            <div class="article-content">
                <p>Trong trường hợp một trong Hai Bên muốn đơn phương chấm dứt Hợp đồng trước hạn thì phải thông báo bằng văn bản cho bên kia trước <strong>30 (ba mươi) ngày</strong> so với ngày mong muốn chấm dứt. Nếu một trong Hai Bên không thực hiện nghĩa vụ thông báo cho Bên kia thì sẽ phải bồi thường cho bên đó một khoản tiền thuê tương đương với thời gian không thông báo và các thiệt hại khác phát sinh do việc chấm dứt Hợp đồng trái quy định.</p>
            </div>
        </div>

        <div class="article">
            <div class="article-title">Điều 10. Điều khoản thi hành:</div>
            <div class="article-content">
                <p>- Hợp đồng này có hiệu lực kể từ ngày hai bên cùng ký kết;</p>
                <p>- Các Bên cam kết thực hiện nghiêm chỉnh và đầy đủ các thoả thuận trong Hợp đồng này trên tinh thần hợp tác, thiện chí;</p>
                <p>- Mọi sửa đổi, bổ sung đối với bất kỳ điều khoản nào của Hợp đồng phải được lập thành văn bản, có đầy đủ chữ ký của mỗi Bên;</p>
                <p>- Hợp đồng được lập thành <strong>02 (hai) bản</strong> có giá trị như nhau, mỗi Bên giữ <strong>01 (một) bản</strong> để thực hiện.</p>
            </div>
        </div>

        <div class="signature-section">
            <div class="signature-box">
                <div class="signature-line"></div>
                <div class="signature-label">BÊN CHO THUÊ</div>
                <div style="margin-top: 10px; font-size: 14px; color: #6b7280;">
                    (ký và ghi rõ họ tên)
                </div>
            </div>
            <div class="signature-box">
                <div class="signature-line"></div>
                <div class="signature-label">BÊN THUÊ</div>
                <div style="margin-top: 10px; font-size: 14px; color: #6b7280;">
                    (ký và ghi rõ họ tên)
                </div>
            </div>
        </div>

        <div class="footer">
            <p>Hợp đồng được tạo tự động bởi hệ thống quản lý khu trọ</p>
            <p>Ngày tạo: ${currentDate} | Mã hợp đồng: ${contractId || 'N/A'}</p>
        </div>
    </div>
</body>
</html>`
}

/**
 * Handle error messages based on error codes
 */
export function getErrorMessage(error: any): string {
    const errorObj = error as any

    if (errorObj?.code === '23505') {
        if (errorObj?.details?.includes('cccd')) {
            return 'CCCD đã tồn tại trong hệ thống. Vui lòng kiểm tra lại.'
        } else if (errorObj?.details?.includes('email')) {
            return 'Email đã tồn tại trong hệ thống. Vui lòng kiểm tra lại.'
        } else {
            return 'Thông tin khách thuê đã tồn tại. Vui lòng kiểm tra lại.'
        }
    } else if (errorObj?.code === '409') {
        return 'Có lỗi xung đột dữ liệu. Vui lòng thử lại.'
    } else {
        return 'Có lỗi xảy ra khi tạo hợp đồng thuê. Vui lòng thử lại.'
    }
}

/**
 * Create initial form data
 */
export function createInitialFormData(): TenantFormData {
    return {
        name: '',
        address: '',
        phone: '',
        email: '',
        cccd: '',
        rentMonths: 12
    }
}
